"""updates Review table

Revision ID: 0e69bcb1cc1f
Revises: 6944bcb4ce60
Create Date: 2024-10-05 16:36:00.008023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e69bcb1cc1f'
down_revision = '6944bcb4ce60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_reviews_customer_id_customers'),'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_item_id_items'), 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_item_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_customer_id_customers'), type_='foreignkey')
    # ### end Alembic commands ###
